### ISSUE TITLE
dokumentasi untuk linux/ubuntu di dokumentasi perlu di update

### ISSUE THREAD

**Issue by dodolboks** [graphteon/luwak#10]
saya mengikuti panduan di dokumentasi untuk installasi luwak di ubuntu 22.04 dan tidak berhasil karena libssl tidak bisa di unduh, bisa di update dengan libssl di link berikut  http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.20_amd64.deb

**Comment by anak10thn** [comment]
sudah di fixed yah @dodolboks
